name: Build & Release
on: push

jobs:
  build:
    name: Checkout & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      #
      # ADD TEST/BUILD STEPS HERE
      #

  publish:
    name: Check version & Create release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: EndBug/version-check@v1
      id: check
      with:
        file-name: haxelib.json
        diff-search: true
    - name: Create Release
      if: steps.check.outputs.changed
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.check.outputs.version }}
        # tag_name: ${{ github.ref }}
        release_name: ${{ steps.check.outputs.version }}
        # release_name: ${{ github.ref }}
        draft: false
        prerelease: false
