name: haxelib-publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with
          haxe-version: 4.1.2
      - run: |
          haxe -version
          haxelib submit . ${{ secrets.HAXELIB_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}