name: haxelib-publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.0.0
      - name: Expose Haxelib
        uses: endel/expose-haxelib-action@master
        id: haxelib
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.2
      - run: |
          haxe -version
          haxelib submit . ${{ secrets.HAXELIB_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        if: steps.haxelib.outputs.name
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.haxelib.outputs.version }}
          release_name: ${{ steps.haxelib.outputs.version }}
          body: ${{ steps.haxelib.outputs.releasenote }}
          draft: false
          prerelease: false